spring.application.name=kafka-stub

# Подключение к БД
spring.datasource.url=jdbc:postgresql://localhost:5432/performance_db
spring.datasource.username=user
spring.datasource.password=password

# Меняем на 'create', чтобы принудительно стирать и создавать таблицу заново при каждом запуске!
# validate - добавить данные в таблицу, есть ещё update, вроде как создать новую
spring.jpa.hibernate.ddl-auto=create
# ВКЛ.ВЫКЛ вывод системных SQL-запросов Hibernate на экран true
spring.jpa.show-sql=false

# Подключение к Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=performance-stub-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# --- ДОБАВЛЯЕМ СТРОГИЙ ТАЙМАУТ ДЛЯ КАФКИ (чтобы она не вешала приложение) ---
spring.kafka.properties.max.block.ms=5000

# Отключаем вывод системных SQL-запросов Hibernate на экран

# --- ВКЛ.ВЫКЛ ПОДРОБНЫЕ ЛОГИ SPRING BOOT --- INFO WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# Открываем все веб-точки (endpoints) Actuator наружу
management.endpoints.web.exposure.include=*
# Включаем сбор метрик Prometheus
management.endpoint.prometheus.enabled=true
# Разрешаем выводить метрики JVM в подробном формате
management.metrics.export.prometheus.enabled=true

