spring.application.name=kafka-stub

# Подключение к БД
spring.datasource.url=jdbc:postgresql://localhost:5432/performance_db
spring.datasource.username=user
spring.datasource.password=password

# Меняем на 'create', чтобы принудительно стирать и создавать таблицу заново при каждом запуске!
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Подключение к Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=performance-stub-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# --- ДОБАВЛЯЕМ СТРОГИЙ ТАЙМАУТ ДЛЯ КАФКИ (чтобы она не вешала приложение) ---
spring.kafka.properties.max.block.ms=5000

# --- ВКЛЮЧАЕМ ПОДРОБНЫЕ ЛОГИ SPRING BOOT ---
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
